version: '3'
services:
  server:
    build: server/
    command: python3 -u ./server.py
    volumes:
      - ./server:/server
    depends_on:
      - database
    environment:
      MAX_CLIENTS: 5
      ANALYZERS_NUMBER: 4
      RESPONSORS_NUMBER: 4
      DISPATCHERS_NUMBER: 4
    networks:
      net:
        ipv4_address: 172.28.1.1

  ftp_server:
    image: delfer/alpine-ftp-server
    ports:
      - '21:21'
      - '21000-21010:21000-21010'
    volumes:
      - ./ftp_server/ftp:/ftp/ftp
    environment:
      ADDRESS: '172.28.1.3'
      USERS: 'username|mypass'
    networks:
      # - net
      net:
        ipv4_address: 172.28.1.3

  database:
    build: database/
    command: python3 -u ./database.py
    volumes:
      - ./database:/database
    environment:
      MAX_RESPONSORS: 4
      MAX_ANALYZERS: 4
      RESOLVERS_NUMBER: 4
      PERSISTORS_NUMBER: 4
    networks:
      net:
        ipv4_address: 172.28.1.4

  client:
    build: client/
    command: python3 ./client.py -a 172.28.1.3
    volumes:
      - ./client:/client
    depends_on:
      - server
    networks:
      - net

networks:
  net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
