version: '3'
services:
  server:
    build: server/
    command: python3 -u ./server.py
    volumes:
      - ./server:/server
    depends_on:
      - ftp_server
    networks:
      net:
        ipv4_address: 172.28.1.1

  client_analyze:
    build: client/
    command: python3 ./client.py -a 172.28.1.3
    volumes:
      - ./client:/client
    depends_on:
      - server
    networks:
      net:
        ipv4_address: 172.28.1.2

  # client_report:
  #   build: client/
  #   command: python3 ./client.py -r sarasa
  #   volumes:
  #     - ./client:/client
  #   depends_on:
  #     - server
  #   networks:
  #     net:
  #       ipv4_address: 172.28.1.4

  ftp_server:
    image: delfer/alpine-ftp-server
    ports:
      - '21:21'
      - '21000-21010:21000-21010'
    volumes:
      - ./ftp_server/ftp:/ftp/ftp
    environment:
      ADDRESS: '172.28.1.3'
      USERS: 'username|mypass'
    networks:
      net:
        ipv4_address: 172.28.1.3

  # database:
  #   build: database/
  #   command: python3 ./database.py
  #   volumes:
  #     - ./database:/database

networks:
  net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
