version: '3'
services:
  server:
    build: server/
    command: python3 -u ./server.py
    volumes:
      - ./server:/server

  client_analyze:
    build: client/
    command: python3 ./client.py -a sarasa
    volumes:
      - ./client:/client
    depends_on:
      - server

  client_report:
    build: client/
    command: python3 ./client.py -r sarasa
    volumes:
      - ./client:/client
    depends_on:
      - server
