version: '3'
services:
  rabbitmq:
    image: rabbitmq:3.7.14-management
    ports:
      - '15672:15672'
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "15672" ]
      interval: 5s
      timeout: 15s
      retries: 10

  server:
    build: server
    command: python3 -u ./server.py
    volumes:
      - ./server:/server
    depends_on:
      - rabbitmq
    restart: on-failure

  client:
    build: client
    command: python3 -u ./client.py
    volumes:
      - ./client:/client
    depends_on:
      - rabbitmq
    restart: on-failure
