version: '3'
services:
  rabbitmq:
    image: rabbitmq:3.7.14-management
    ports:
      - '15672:15672'
    # healthcheck:
    #   test: [ "CMD", "nc", "-z", "localhost", "15672" ]
    #   interval: 5s
    #   timeout: 15s
    #   retries: 10

  surface_dispatcher:
    build: surface_dispatcher
    command: python3 -u ./surface_dispatcher.py
    volumes:
      - ./surface_dispatcher:/surface_dispatcher
    depends_on:
      - rabbitmq
    restart: on-failure

  hard_accumulator:
    build: accumulator
    environment:
      ROUTING_KEY: Hard
    command: python3 -u ./accumulator.py
    volumes:
      - ./accumulator:/accumulator
    depends_on:
      - rabbitmq
    restart: on-failure

  clay_accumulator:
    build: accumulator
    environment:
      ROUTING_KEY: Clay
    command: python3 -u ./accumulator.py
    volumes:
      - ./accumulator:/accumulator
    depends_on:
      - rabbitmq
    restart: on-failure

  grass_carpet_accumulator:
    build: accumulator
    environment:
      ROUTING_KEY: Grass-Carpet
    command: python3 -u ./accumulator.py
    volumes:
      - ./accumulator:/accumulator
    depends_on:
      - rabbitmq
    restart: on-failure

  average_calculator:
    build: average_calculator
    command: python3 -u ./average_calculator.py
    volumes:
      - ./average_calculator:/average_calculator
    depends_on:
      - rabbitmq
    restart: on-failure

  joiner:
    build: joiner
    command: python3 -u ./joiner.py
    volumes:
      - ./joiner:/joiner
    depends_on:
      - rabbitmq
    restart: on-failure

  client:
    build: client
    command: python3 -u ./client.py
    volumes:
      - ./client:/client
    depends_on:
      - rabbitmq
    restart: on-failure
