version: '2.4'
services:
  rabbitmq:
    image: rabbitmq:3.7.14-management
    ports:
      - '15672:15672'
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "check_port_connectivity"]
      interval: 5s
      timeout: 15s
      retries: 10

  surface_dispatcher:
    build: surface_dispatcher
    command: python3 -u ./surface_dispatcher.py
    volumes:
      - ./surface_dispatcher:/surface_dispatcher
    depends_on:
      rabbitmq:
        condition: service_healthy

  hard_accumulator:
    build: accumulator
    environment:
      ROUTING_KEY: Hard
      EXCHANGE: surfaces
      OUTPUT_QUEUE: surface_values
    command: python3 -u ./accumulator.py
    volumes:
      - ./accumulator:/accumulator
    depends_on:
      rabbitmq:
        condition: service_healthy

  clay_accumulator:
    build: accumulator
    environment:
      ROUTING_KEY: Clay
      EXCHANGE: surfaces
      OUTPUT_QUEUE: surface_values
    command: python3 -u ./accumulator.py
    volumes:
      - ./accumulator:/accumulator
    depends_on:
      rabbitmq:
        condition: service_healthy

  grass_carpet_accumulator:
    build: accumulator
    environment:
      ROUTING_KEY: Grass-Carpet
      EXCHANGE: surfaces
      OUTPUT_QUEUE: surface_values
    command: python3 -u ./accumulator.py
    volumes:
      - ./accumulator:/accumulator
    depends_on:
      rabbitmq:
        condition: service_healthy

  average_calculator:
    build: average_calculator
    command: python3 -u ./average_calculator.py
    volumes:
      - ./average_calculator:/average_calculator
    depends_on:
      rabbitmq:
        condition: service_healthy

  joiner:
    build: joiner
    command: python3 -u ./joiner.py
    volumes:
      - ./joiner:/joiner
    depends_on:
      rabbitmq:
        condition: service_healthy

  age_calculator:
    build: age_calculator
    command: python3 -u ./age_calculator.py
    volumes:
      - ./age_calculator:/age_calculator
    depends_on:
      rabbitmq:
        condition: service_healthy

  age_difference_filter:
    build: age_difference_filter
    command: python3 -u ./age_difference_filter.py
    volumes:
      - ./age_difference_filter:/age_difference_filter
    depends_on:
      rabbitmq:
        condition: service_healthy

  different_hands_filter:
    build: different_hands_filter
    command: python3 -u ./different_hands_filter.py
    volumes:
      - ./different_hands_filter:/different_hands_filter
    depends_on:
      rabbitmq:
        condition: service_healthy

  right_accumulator:
    build: accumulator
    environment:
      ROUTING_KEY: R
      EXCHANGE: hands
      OUTPUT_QUEUE: hands_values
    command: python3 -u ./accumulator.py
    volumes:
      - ./accumulator:/accumulator
    depends_on:
      rabbitmq:
        condition: service_healthy

  left_accumulator:
    build: accumulator
    environment:
      ROUTING_KEY: L-U
      EXCHANGE: hands
      OUTPUT_QUEUE: hands_values
    command: python3 -u ./accumulator.py
    volumes:
      - ./accumulator:/accumulator
    depends_on:
      rabbitmq:
        condition: service_healthy

  percentage_calculator:
    build: percentage_calculator
    command: python3 -u ./percentage_calculator.py
    volumes:
      - ./percentage_calculator:/percentage_calculator
    depends_on:
      rabbitmq:
        condition: service_healthy

  client:
    build: client
    command: python3 -u ./client.py
    volumes:
      - ./client:/client
    depends_on:
      rabbitmq:
        condition: service_healthy
    depends_on:
      - joiner

  database:
    build: database
    command: python3 -u ./database.py
    depends_on:
      rabbitmq:
        condition: service_healthy
